
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cjftn
 */
public class DBView extends javax.swing.JFrame {
    sqlDB db=new sqlDB();
    BufferedImage im10=null;
    /**
     * Creates new form DBView
     */
    public DBView() throws SQLException {
        initComponents();
        setTitle("게임 점수");
        try {
            im10=ImageIO.read(Menu.class.getResource("image/나가기.png"));
        } catch (Exception e) {
            System.out.println(e);
        }
        jButton4.setIcon(new ImageIcon(im10));
        jButton4.setContentAreaFilled(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jL8 = new javax.swing.JLabel();
        jL9 = new javax.swing.JLabel();
        jL10 = new javax.swing.JLabel();
        jL11 = new javax.swing.JLabel();
        jL12 = new javax.swing.JLabel();
        jL13 = new javax.swing.JLabel();
        jL14 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setText("닫기");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 2));

        jL1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jL1.setText("1");
        jL1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jL1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jL1);

        jL2.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL2);

        jL3.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL3);

        jL4.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL4);

        jL5.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL5);

        jL6.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL6);

        jL7.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL7);

        jL8.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL8);

        jL9.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL9);

        jL10.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL10);

        jL11.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL11);

        jL12.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL12);

        jL13.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL13);

        jL14.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel1.add(jL14);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane2);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        jLabel1.setText("게임순위");

        jButton1.setText("한글순위");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("영어순위");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("코딩순위");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel17.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel17.setText("1 등 ");
        jPanel2.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel18.setText("2 등");
        jPanel2.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel19.setText("3 등");
        jPanel2.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel20.setText("4 등");
        jPanel2.add(jLabel20);

        jLabel21.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel21.setText("5 등");
        jPanel2.add(jLabel21);

        jLabel22.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel22.setText("6 등");
        jPanel2.add(jLabel22);

        jLabel23.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel23.setText("7 등");
        jPanel2.add(jLabel23);

        jLabel24.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel24.setText("8 등 ");
        jPanel2.add(jLabel24);

        jLabel25.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel25.setText("9 등");
        jPanel2.add(jLabel25);

        jLabel26.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel26.setText("10등");
        jPanel2.add(jLabel26);

        jLabel27.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel27.setText("11등");
        jPanel2.add(jLabel27);

        jLabel28.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel28.setText("12등");
        jPanel2.add(jLabel28);

        jLabel29.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel29.setText("13등");
        jPanel2.add(jLabel29);

        jLabel30.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel30.setText("14등");
        jPanel2.add(jLabel30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jL1.setText("");
        jL2.setText("");
        jL3.setText("");
        jL4.setText("");
        jL5.setText("");
        jL6.setText("");
        jL7.setText("");
        jL8.setText("");
        jL9.setText("");
        jL10.setText("");
        jL11.setText("");
        jL12.setText("");
        jL13.setText("");
        jL14.setText("");
        try {
            ArrayList a=db.select("한글게임");
            //for (int i = 0; i < a.size(); i++) {
                
                jL1.setText((String) a.get(0));
                jL2.setText((String) a.get(1));
                jL3.setText((String) a.get(2));
                jL4.setText((String) a.get(3));
                jL5.setText((String) a.get(4));
                jL6.setText((String) a.get(5));
                jL7.setText((String) a.get(6));
                jL8.setText((String) a.get(7));
                jL9.setText((String) a.get(8));
                jL10.setText((String) a.get(9));
                jL11.setText((String) a.get(10));
                jL12.setText((String) a.get(11));
                jL13.setText((String) a.get(12));
                jL14.setText((String) a.get(13));
           //}
            
        } catch (SQLException ex) {
            Logger.getLogger(DBView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jL1.setText("");
        jL2.setText("");
        jL3.setText("");
        jL4.setText("");
        jL5.setText("");
        jL6.setText("");
        jL7.setText("");
        jL8.setText("");
        jL9.setText("");
        jL10.setText("");
        jL11.setText("");
        jL12.setText("");
        jL13.setText("");
        jL14.setText("");
        try {
            ArrayList a=db.select("영어게임");
            //for (int i = 0; i < a.size(); i++) {
                
                jL1.setText((String) a.get(0));
                jL2.setText((String) a.get(1));
                jL3.setText((String) a.get(2));
                jL4.setText((String) a.get(3));
                jL5.setText((String) a.get(4));
                jL6.setText((String) a.get(5));
                jL7.setText((String) a.get(6));
                jL8.setText((String) a.get(7));
                jL9.setText((String) a.get(8));
                jL10.setText((String) a.get(9));
                jL11.setText((String) a.get(10));
                jL12.setText((String) a.get(11));
                jL13.setText((String) a.get(12));
                jL14.setText((String) a.get(13));
           //}
            
        } catch (SQLException ex) {
            Logger.getLogger(DBView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jL1.setText("");
        jL2.setText("");
        jL3.setText("");
        jL4.setText("");
        jL5.setText("");
        jL6.setText("");
        jL7.setText("");
        jL8.setText("");
        jL9.setText("");
        jL10.setText("");
        jL11.setText("");
        jL12.setText("");
        jL13.setText("");
        jL14.setText("");
        try {
            ArrayList a=db.select("코딩게임");
            //for (int i = 0; i < a.size(); i++) {
                
                jL1.setText((String) a.get(0));
                jL2.setText((String) a.get(1));
                jL3.setText((String) a.get(2));
                jL4.setText((String) a.get(3));
                jL5.setText((String) a.get(4));
                jL6.setText((String) a.get(5));
                jL7.setText((String) a.get(6));
                jL8.setText((String) a.get(7));
                jL9.setText((String) a.get(8));
                jL10.setText((String) a.get(9));
                jL11.setText((String) a.get(10));
                jL12.setText((String) a.get(11));
                jL13.setText((String) a.get(12));
                jL14.setText((String) a.get(13));
           //}
            
        } catch (SQLException ex) {
            Logger.getLogger(DBView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jL1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jL1AncestorAdded
        
        try {
            ArrayList a=db.print();
            //for (int i = 0; i < a.size(); i++) {
                
                jL1.setText((String) a.get(0));
                jL2.setText((String) a.get(1));
                jL3.setText((String) a.get(2));
                jL4.setText((String) a.get(3));
                jL5.setText((String) a.get(4));
                jL6.setText((String) a.get(5));
                jL7.setText((String) a.get(6));
                jL8.setText((String) a.get(7));
                jL9.setText((String) a.get(8));
                jL10.setText((String) a.get(9));
                jL11.setText((String) a.get(10));
                jL12.setText((String) a.get(11));
                jL13.setText((String) a.get(12));
                jL14.setText((String) a.get(13));
           //}
            
        } catch (SQLException ex) {
            Logger.getLogger(DBView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jL1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DBView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DBView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL13;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
